# Header
menu:
  首页: /
  留言: /messages
  关于: /about

# 主页banner图
banner: http://rj64n9iaf.hb-bkt.clouddn.com/image/birthday.jpg

# 站点通知信息
notice: ~热烈庆祝小蘇同学破壳~

# 作者信息
author:
  name: 雨
  avatar: http://rj64n9iaf.hb-bkt.clouddn.com/image/%E5%A6%82%E7%87%95.jpg
  description: 

toc:
  max_depth: 3 # 生成 TOC 的最大深度
  min_depth: 2 # 生成 TOC 的最小深度

comments:
  enable: true
  # use: 'valine' # valine || disqus
  # valine 评论
  # docs: https://valine.js.org
  # You can get your appid and appkey from https://leancloud.cn
  # 这里appId和appKey一定一定要改成自己的，没有的话去https://leancloud.cn这个网站注册创建一个

# dplayer 视频播放
# docs: http://dplayer.js.org/#/zh-Hans/
dplayer:
  enable: true
  theme: "#b7daff"
  autoplay: false
  loop: false
  mutex: true

# aplayer 音频播放
# docs: https://aplayer.js.org/#/zh-Hans/
aplayer:
  enable: true
  theme: "#b7daff"
  autoplay: true
  mutex: true
  lrcType: 3

# 国内备案信息
beian: 

# 谷歌分析
google_analytics: 
# gauges分析
gauges_analytics: 
# 百度分析
baidu_analytics: 
# 腾讯分析
tencent_analytics: 
# 站点ico
favicon: /favicon.ico


# Social Icon
social_icon:
  enable: true
  icons:
    ins     :
    zhihu   :
    weibo   : 
    github  : https://github.com/HWAZWD
    #twitter : https://twitter.com/guanquanhong